list(APPEND BFSUPPORT_CMAKE_ARGS
    -DBAREFLANK_SOURCE_DIR=${BAREFLANK_SOURCE_DIR}
    -DBAREFLANK_BINARY_DIR=${BAREFLANK_BINARY_DIR}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
    -DENABLE_COVERAGE=${ENABLE_COVERAGE}
    -DENABLE_DYNAMIC_ASAN=${ENABLE_DYNAMIC_ASAN}
    -DENABLE_DYNAMIC_USAN=${ENABLE_DYNAMIC_USAN}
    -DENABLE_TIDY=${ENABLE_TIDY}
    -DENABLE_ASTYLE=${ENABLE_ASTYLE}
    -DENABLE_UNITTESTING=${ENABLE_UNITTESTING}
    -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
    -DBUILD_STATIC_LIBS=${BUILD_STATIC_LIBS}
)

ExternalProject_Add(
    bfsupport
    CMAKE_ARGS      ${BFSUPPORT_CMAKE_ARGS}
    # PREFIX          ${CMAKE_BINARY_DIR}/bfsupport/prefix
    # TMP_DIR         ${CMAKE_BINARY_DIR}/bfsupport/tmp
    # STAMP_DIR       ${CMAKE_BINARY_DIR}/bfsupport/stamp
    SOURCE_DIR      ${CMAKE_SOURCE_DIR}/bfsysroot/bfsupport
    # BINARY_DIR      ${CMAKE_BINARY_DIR}/bfsupport/build
    UPDATE_DISCONNECTED 0
    UPDATE_COMMAND      ""
    DEPENDS         newlib libcxxabi libcxx
)
