list(APPEND LIBCXXABI_C_FLAGS
    ${C_FLAGS_VMM}
)
string(REPLACE ";" " " LIBCXXABI_C_FLAGS "${LIBCXXABI_C_FLAGS}")

list(APPEND LIBCXXABI_CXX_FLAGS
    ${CXX_FLAGS_VMM}
    "-I${BUILD_SYSROOT_VMM}/include"
    "-I${BUILD_SYSROOT_VMM}/include/sys"
)
string(REPLACE ";" " " LIBCXXABI_CXX_FLAGS "${LIBCXXABI_CXX_FLAGS}")

list(APPEND LIBCXXABI_CMAKE_ARGS
	-DLLVM_PATH=${BF_BUILD_DEPENDS_DIR}/src/llvm
	-DLLVM_ENABLE_LIBCXX=ON
    -DLIBCXXABI_LIBCXX_PATH=${BF_BUILD_DEPENDS_DIR}/src/libcxx
    -DLIBCXXABI_SYSROOT=${BUILD_SYSROOT_VMM}
    -DLIBCXXABI_HAS_PTHREAD_API=ON
    -DCMAKE_INSTALL_PREFIX=${BUILD_SYSROOT_VMM}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}
    -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_PATH_LIBCXXABI}
    -DCMAKE_C_FLAGS=${LIBCXXABI_C_FLAGS}
    -DCMAKE_CXX_FLAGS=${LIBCXXABI_CXX_FLAGS}
    -DBUILD_SYSROOT_VMM=${BUILD_SYSROOT_VMM}
)

if(BUILD_SHARED_LIBS)
    list(APPEND LIBCXXABI_CMAKE_ARGS -DLIBCXXABI_ENABLE_SHARED=ON -DLIBCXXABI_ENABLE_STATIC=OFF)
endif()

if(BUILD_STATIC_LIBS)
    list(APPEND LIBCXXABI_CMAKE_ARGS -DLIBCXXABI_ENABLE_STATIC=ON -DLIBCXXABI_ENABLE_SHARED=OFF)
endif()

ExternalProject_Add(
    libcxxabi
    GIT_REPOSITORY      https://github.com/Bareflank/libcxxabi.git
    GIT_TAG             v1.2
    GIT_SHALLOW         1
    SOURCE_DIR      	${BF_BUILD_DEPENDS_DIR}/src/libcxxabi
	CMAKE_ARGS      	${LIBCXXABI_CMAKE_ARGS}
    UPDATE_DISCONNECTED 0
    UPDATE_COMMAND      ""
    DEPENDS libcxx_download libcxxabi_download llvm bfunwind bfsdk binutils
)
