list(APPEND LIBCXX_C_FLAGS
    ${C_FLAGS_VMM}
)
string(REPLACE ";" " " LIBCXX_C_FLAGS "${LIBCXX_C_FLAGS}")

list(APPEND LIBCXX_CXX_FLAGS
    ${CXX_FLAGS_VMM}
    "-I${BF_BUILD_INSTALL_DIR}/include"
    "-I${BF_BUILD_INSTALL_DIR}/include/sys"
)
string(REPLACE ";" " " LIBCXX_CXX_FLAGS "${LIBCXX_CXX_FLAGS}")

list(APPEND LIBCXX_CMAKE_ARGS
	-DLLVM_PATH=${BF_BUILD_DEPENDS_DIR}/src/llvm
    -DLIBCXX_CXX_ABI=libcxxabi
    -DLIBCXX_CXX_ABI_INCLUDE_PATHS=${BF_BUILD_DEPENDS_DIR}/src/libcxxabi/include/
    -DLIBCXX_SYSROOT=${BF_BUILD_INSTALL_DIR}
	-DLIBCXX_HAS_PTHREAD_API=ON
	-DLIBCXX_ENABLE_EXPERIMENTAL_LIBRARY=OFF
    -DCMAKE_INSTALL_PREFIX=${BF_BUILD_INSTALL_DIR}
	-DCMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}
    -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_PATH_LIBCXX}
	-DCMAKE_C_FLAGS=${LIBCXX_C_FLAGS}
	-DCMAKE_CXX_FLAGS=${LIBCXX_CXX_FLAGS}
)

if(BUILD_SHARED_LIBS)
    list(APPEND LIBCXX_CMAKE_ARGS -DLIBCXX_ENABLE_SHARED=ON -DLIBCXX_ENABLE_STATIC=OFF)
endif()

if(BUILD_STATIC_LIBS)
    list(APPEND LIBCXX_CMAKE_ARGS -DLIBCXX_ENABLE_STATIC=ON -DLIBCXX_ENABLE_SHARED=OFF)
endif()

ExternalProject_Add(
    libcxx
	GIT_REPOSITORY      https://github.com/Bareflank/libcxx.git
	GIT_TAG             v1.2
	GIT_SHALLOW         1
    UPDATE_DISCONNECTED 0
    UPDATE_COMMAND      ""
    SOURCE_DIR      	${BF_BUILD_DEPENDS_DIR}/src/libcxx
	CMAKE_ARGS      	${LIBCXX_CMAKE_ARGS}
    DEPENDS libcxx_download libcxxabi_download llvm bfunwind libcxxabi bfsdk binutils
)
