list(APPEND LIBCXX_CXX_FLAGS
    "-I${BUILD_SYSROOT_VMM}/include"
    "-I${BUILD_SYSROOT_VMM}/include/sys"
)

generate_flags(
    VMM
    ADD_CXX_FLAGS ${LIBCXX_CXX_FLAGS}
    C_FLAGS_OUT LIBCXX_C_FLAGS
    CXX_FLAGS_OUT LIBCXX_CXX_FLAGS
    SILENT
)

list(APPEND LIBCXX_CMAKE_ARGS
	-DLLVM_PATH=${BF_BUILD_DEPENDS_DIR}/src/llvm
    -DLIBCXX_CXX_ABI=libcxxabi
    -DLIBCXX_CXX_ABI_INCLUDE_PATHS=${BF_BUILD_DEPENDS_DIR}/src/libcxxabi/include/
    -DLIBCXX_SYSROOT=${BUILD_SYSROOT_VMM}
	-DLIBCXX_HAS_PTHREAD_API=ON
	-DLIBCXX_ENABLE_EXPERIMENTAL_LIBRARY=OFF
    -DCMAKE_INSTALL_PREFIX=${BUILD_SYSROOT_VMM}
	-DCMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}
    -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_PATH_LIBCXX}
	-DCMAKE_C_FLAGS=${LIBCXX_C_FLAGS}
	-DCMAKE_CXX_FLAGS=${LIBCXX_CXX_FLAGS}
    -DBUILD_SYSROOT_VMM=${BUILD_SYSROOT_VMM}
)

if(BUILD_VMM_SHARED)
    list(APPEND LIBCXX_CMAKE_ARGS -DLIBCXX_ENABLE_SHARED=ON)
endif()

if(BUILD_VMM_STATIC)
    list(APPEND LIBCXX_CMAKE_ARGS -DLIBCXX_ENABLE_STATIC=ON)
endif()

ExternalProject_Add(
    libcxx
	GIT_REPOSITORY      https://github.com/Bareflank/libcxx.git
	GIT_TAG             v1.2
	GIT_SHALLOW         1
    UPDATE_DISCONNECTED 0
    UPDATE_COMMAND      ""
    SOURCE_DIR      	${BF_BUILD_DEPENDS_DIR}/src/libcxx
	CMAKE_ARGS      	${LIBCXX_CMAKE_ARGS}
    DEPENDS libcxx_download libcxxabi_download llvm bfunwind libcxxabi bfsdk binutils
)
